import AppLayout from '@/components/layout/AppLayout';
import StudyPlanClient from '@/components/StudyPlanClient';

export default function StudyPlanPage() {
  return (
    <AppLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold tracking-tight font-headline">AI Study Plan</h1>
          <p className="text-muted-foreground">
            Get a personalized study plan generated by AI to help you improve your cognitive skills.
          </p>
        </div>
        <StudyPlanClient />
      </div>
    </AppLayout>
  );
}
